name: Build
on: [push, pull_request]
env:
  TERM: xterm-256color

defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Build with Zig"
    runs-on: macos-11
    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.9.9
      - name: Set up Golang
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17.5
      - name: System information
        run: xcrun --show-sdk-path
      - name: Run local build
        run: ./build-native.sh shared
      - name: Run cross-compilation build
        run: ./build-cross.sh shared $(uname | tr '[:upper:]' '[:lower:]') $(uname -m)
